/*
 * hm_bt_api.h
 *
 *  Created on: May 23, 2014
 *      Author: cannedapps
 */

#ifndef HM_BT_API_H_
#define HM_BT_API_H_

#define PACKET_BEGIN    0x00
#define PACKET_END      0xFF
#define PACKET_ESCAPE   0xFE

//BT Commands
#define ID_RESTART_SOFTWARE       0xAA

#define ID_ACK_COMMAND   0x01
#define ID_ERROR         0x02

//TODO REMOVE OLD AUTH
#define ID_SET_AUTHENTICATION_PASSWORD 	0x20
#define ID_CREATE_AUTHENTICATION_TOKEN 	0x21
#define ID_REVOKE_AUTHENTICATION_TOKEN 	0x22
#define ID_AUTHENTICATE 			   	0x23

#define ID_START_PING 			0x24
#define ID_STOP_PING 			0x25
#define ID_PING_NOTIFICATION 	0x26

#define ID_CUSTOM_COMMAND	 	0x27

#define ID_CRYPTO_GET_NONCE 0x30
#define ID_CRYPTO_GET_DEVICE_CERTIFICATE 0x31
#define ID_CRYPTO_REGISTER_CERTIFICATE 0x32
#define ID_CRYPTO_STORE_CERTIFICATE 0x33
#define ID_CRYPTO_GET_CERTIFICATE 0x34
#define ID_CRYPTO_AUTHENTICATE 0x35
#define ID_CRYPTO_CONTAINER 0x36
#define ID_CRYPTO_RESET 0x37
#define ID_CRYPTO_REVOKE 0x38

#define ID_REQUEST_USER_FEEDBACK 0x39

#define ID_READ_STORAGE			0xE1
#define ID_WRITE_STORAGE		0xE2
#define ID_DELETE_STORAGE 	    0xE3

#define ID_BEACON_ZONE_CALCULATED      0xB5
#define ID_BEACON_REPORT_RECEIVED      0xB6
#define ID_BEACON_SET_RADAR_RULE       0xB7

#define ID_WRITE_GP_OUTPUT 	0x0C
#define ID_READ_GP_INPUT 	0x0D

#define ID_WRITE_STD_CAN_FRAME   				0x03
#define ID_WRITE_EXT_CAN_FRAME   				0x04
#define ID_READ_STD_CAN_FRAME    				0x05
#define ID_READ_EXT_CAN_FRAME    				0x06
#define ID_GET_CAN_FILTERING_ENABLED_STATUS     0x07
#define ID_SET_CAN_FILTERING_ENABLED_STATUS     0x08
#define ID_GET_CAN_FILTER                    	0x09
#define ID_SET_CAN_FILTER 						0x0A
#define ID_GET_CAN_SYSTEM_STATUS 				0x0B // TODO: error count, packet count, etc.
#define ID_WRITE_ISO_MESSAGE 					0x0F
#define ID_READ_ISO_MESSAGE 					0x10

//BT Errors

#define ERR_INTERNAL_ERROR       0x01
#define ERR_COMMAND_EMPTY        0x02
#define ERR_COMMAND_UNKNOWN      0x03
#define ERR_INVALID_DATA         0x04
#define ERR_STORAGE_FULL         0x05
#define ERR_INVALID_SIGNATURE    0x06
#define ERR_UNAUTHORISED         0x07
#define ERR_INVALID_HMAC         0x08
#define ERR_TIMEOUT              0x09

#endif /* HM_BT_API_H_ */
